
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xe2\xf6\x87\xc8\x11d\xde\x97\xaa7\x9e\x1e\xd5\xfb\x9c\xd5'
    
_lr_action_items = {'RPAREN':([1,2,4,7,9,10,11,],[-2,-5,-4,10,-3,-6,-1,]),'NUMBER':([0,3,6,8,],[2,2,2,2,]),'TIMES':([1,2,4,9,10,11,],[6,-5,-4,-3,-6,6,]),'PLUS':([1,2,4,5,7,9,10,11,],[-2,-5,-4,8,8,-3,-6,-1,]),'LPAREN':([0,3,6,8,],[3,3,3,3,]),'$end':([1,2,4,5,9,10,11,],[-2,-5,-4,0,-3,-6,-1,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'term':([0,3,8,],[1,1,11,]),'expression':([0,3,],[5,7,]),'factor':([0,3,6,8,],[4,4,9,4,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS term','expression',3,'p_expression_plus','/shared/tleng-tp1/ejemplos/codigo_aritmetica/parser_rules.py',7),
  ('expression -> term','expression',1,'p_expression_term','/shared/tleng-tp1/ejemplos/codigo_aritmetica/parser_rules.py',12),
  ('term -> term TIMES factor','term',3,'p_term_times','/shared/tleng-tp1/ejemplos/codigo_aritmetica/parser_rules.py',17),
  ('term -> factor','term',1,'p_term_factor','/shared/tleng-tp1/ejemplos/codigo_aritmetica/parser_rules.py',22),
  ('factor -> NUMBER','factor',1,'p_factor_number','/shared/tleng-tp1/ejemplos/codigo_aritmetica/parser_rules.py',27),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor_expression','/shared/tleng-tp1/ejemplos/codigo_aritmetica/parser_rules.py',32),
]
